default_language_version:
  python: python3.14
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.6
    hooks:
      - id: uv-sync
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff-format
      - id: ruff-check
