services:
  app:
    build: .
    volumes:
      - ./inputs:/srv/inputs
      - ./outputs:/srv/outputs
      - ./tmp:/srv/tmp
    environment:
      - TMP_DIR=/srv/tmp
      - OUTPUT_DIR=/srv/outputs
